"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  QrCode,
  ShieldCheck,
  CheckCircle2,
  Lock,
  Search,
  ArrowRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function ReportVerificationPreview() {
  const router = useRouter();
  const [reportId, setReportId] = React.useState("");

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    const id = reportId.trim() || "REP-2026-001";
    router.push(`/verify/${id}`);
  };

  return (
    <section className="py-20 lg:py-24 bg-[#FFFFFF] border-b border-[#E8E8E3]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-[#171717] rounded-[36px] lg:rounded-[48px] p-8 sm:p-12 lg:p-16 text-white shadow-xl relative overflow-hidden border border-[#262626]">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-center">
            {/* Left Content (7 Cols) */}
            <div className="lg:col-span-7 space-y-5">
              <div className="flex items-center gap-3">
                <span className="text-xs font-serif font-bold text-[#A8D5BA] w-6 h-6 rounded-full border border-[#A8D5BA]/40 flex items-center justify-center">
                  ✓
                </span>
                <div className="h-[1px] w-10 bg-[#A8D5BA]/40" />
                <span className="text-xs uppercase tracking-[0.25em] font-mono text-[#DDEDE3]/80 font-semibold">
                  Online Verification
                </span>
              </div>

              <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl text-white tracking-tight leading-snug font-normal">
                Instant digital report verification
              </h2>

              <p className="text-sm sm:text-base text-[#DDEDE3]/80 leading-relaxed max-w-xl">
                Every diagnostic investigation generated by Apex Diagnostics carries a cryptographically signed QR code. Enter your Report ID below to confirm doctor verification and authenticity.
              </p>

              {/* Verification Form */}
              <form
                onSubmit={handleVerify}
                className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 pt-3 max-w-lg"
              >
                <div className="relative flex-1">
                  <Input
                    type="text"
                    placeholder="Report ID (e.g. REP-2026-001)"
                    value={reportId}
                    onChange={(e) => setReportId(e.target.value)}
                    className="bg-[#222222] border-[#315C4A]/60 text-white placeholder:text-[#70706B] h-12 pl-10 pr-4 rounded-full focus:border-[#A8D5BA]"
                  />
                  <Search className="w-4 h-4 text-[#A8D5BA] absolute left-3.5 top-4" />
                </div>

                <Button
                  type="submit"
                  variant="medical"
                  size="lg"
                  className="h-12 px-7 rounded-full text-xs font-semibold shrink-0"
                >
                  <span>Verify report</span>
                  <ArrowRight className="w-4 h-4 ml-1" />
                </Button>
              </form>

              {/* Sample Quick Links */}
              <div className="pt-2 text-xs text-[#70706B] flex items-center gap-2 font-mono">
                <span>Sample verified IDs:</span>
                <Link
                  href="/verify/REP-2026-001"
                  className="text-[#A8D5BA] hover:underline"
                >
                  REP-2026-001
                </Link>
                <span>•</span>
                <Link
                  href="/verify/REP-2026-002"
                  className="text-[#A8D5BA] hover:underline"
                >
                  REP-2026-002
                </Link>
              </div>
            </div>

            {/* Right Card: Security Credentials Preview (5 Cols) */}
            <div className="lg:col-span-5 bg-[#222222] border border-[#315C4A]/40 rounded-3xl p-6 sm:p-8 space-y-4">
              <div className="flex items-center justify-between pb-3 border-b border-[#315C4A]/30">
                <span className="text-[11px] font-mono text-[#A8D5BA] uppercase">Digital Cryptographic Stamp</span>
                <span className="text-[10px] font-mono text-[#DDEDE3]/60">SHA-256</span>
              </div>

              <div className="flex items-center gap-4">
                <div className="w-16 h-16 rounded-2xl bg-[#171717] border border-[#315C4A]/60 flex items-center justify-center text-[#A8D5BA] shrink-0">
                  <QrCode className="w-10 h-10" />
                </div>
                <div className="space-y-1 text-xs">
                  <p className="font-semibold text-white">Dual Doctor Sign-Off</p>
                  <p className="text-[11px] text-[#70706B] font-mono">BMDC Reg. Certified Consultants</p>
                  <p className="text-[11px] text-[#A8D5BA] font-mono">Tamper-Evident Cloud Storage</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
